package com.secretkiller.app;

import android.app.*; import android.os.*; import android.graphics.*; import android.view.*; import android.widget.*;

public class MainActivity extends Activity {
    LinearLayout root; final int GOLD=Color.rgb(214,168,79),BG=Color.rgb(9,8,12),CARD=Color.rgb(23,21,29),WHITE=Color.rgb(247,241,229),MUTED=Color.rgb(170,165,176),RED=Color.rgb(212,91,99),GREEN=Color.rgb(104,181,139);
    String[] n={"اللاعب ١","اللاعب ٢","اللاعب ٣","اللاعب ٤","اللاعب ٥","اللاعب ٦","اللاعب ٧","اللاعب ٨"};
    String[] r={"بريء — مهندس الأمن","بريء — عالمة الذاكرة","بريء — الطبيب العصبي","بريء — الصحفية المتخفية","بريء — عالم الفيزياء","القاتل","السارق","المتواطئ"};
    String[] s={"عطّلت إنذارًا قبل الحادث لأنك خفت أن يكتشف المدير مخالفة قديمة.","حذفت جزءًا من ذاكرة الدكتور قبل التجربة لأنك خفت من محتواه.","أعطيت أحد المشاركين دواءً مختلفًا دون إخباره.","أنت لست صحفية فعلًا؛ تعملين على كشف الشركة.","صممت جهازًا يعطل جزءًا من النظام دون إذن.","فتحت الممر السري وأغلقت باب الذاكرة أثناء محاولة الدكتور إيقافك. تسبب ذلك في وفاته.","سرقت شريحة الـCore بعد بدء الفوضى. لا تعرف أن القاتل هو من تسبب في موت الدكتور.","بعد الجريمة رأيت دليلًا يربط شخصًا بالممر السري، فخفيته مقابل المال."};
    String[] k={"رأيت بطاقة أمنية قرب الممر الغربي الساعة 21:43.","الدكتور كان يتوقع محاولة سرقة الـCore.","وفاة الدكتور لم تكن نتيجة عطل طبيعي.","رأيت مهندس الأمن يدخل البرج مرتين.","الممر السري لا يظهر في الخريطة العادية.","رأيت شخصًا يحمل الشريحة، لكنك لم ترَ وجهه.","هناك شخص آخر استعمل صلاحية خاصة قبل سرقة الشريحة.","أحد سجلات الأمن تم تعديله بعد الحادث."};
    String[] q={"كنت في غرفة المراقبة عندما بدأ النظام في الانهيار.","كنت أحاول استعادة الذاكرة المحذوفة عندما وقع الحادث.","كنت في المختبر الطبي، ولم أقترب من الممر الغربي.","كنت أبحث عن دليل يدين الشركة عندما بدأ الإنذار.","كنت أختبر جهاز تعطيل الإشارة ولم أكن قرب الدكتور.","كنت في غرفة التحكم عندما بدأ النظام في الانهيار.","كنت أبحث عن مخرج من المنطقة الشرقية عندما انقطع الاتصال.","لم أرَ أي شيء مهم، وكنت أحاول فقط حماية نفسي."};

    public void onCreate(Bundle b){super.onCreate(b);home();}
    TextView t(String x,int z,int c,boolean bold){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.RIGHT);v.setTextDirection(View.TEXT_DIRECTION_RTL);v.setPadding(18,12,18,12);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    Button b(String x){Button v=new Button(this);v.setText(x);v.setTextSize(16);v.setAllCaps(false);v.setTextColor(Color.BLACK);v.setBackgroundColor(GOLD);v.setLayoutParams(new LinearLayout.LayoutParams(-1,62));return v;}
    Button o(String x){Button v=b(x);v.setTextColor(GOLD);v.setBackgroundColor(Color.rgb(40,34,24));return v;}
    void base(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,22,22,22);root.setBackgroundColor(BG);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(root);setContentView(sv);}
    void title(String x){root.addView(t(x,25,WHITE,true));}
    void card(String x){TextView v=t(x,17,WHITE,false);v.setBackgroundColor(CARD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,8,0,8);root.addView(v,p);}
    void home(){base();Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,100));TextView logo=t("SECRET KILLER",42,GOLD,true);logo.setGravity(Gravity.CENTER);root.addView(logo);TextView sub=t("كل قصة تخفي سرًا.",17,MUTED,false);sub.setGravity(Gravity.CENTER);root.addView(sub);Button st=b("ابدأ اللعبة");st.setOnClickListener(v->story());root.addView(st);Button h=o("طريقة اللعب");h.setOnClickListener(v->how());root.addView(h);}
    void story(){base();title("اختيار القصة");card("مدينة الأحلام\n\nجريمة داخل حلم مشترك. ثلاثة مذنبين، لكن كل مذنب لديه معرفة مختلفة.\n\n٦–٨ لاعبين • ٣ مذنبين");Button x=b("اختيار هذه القصة");x.setOnClickListener(v->setup());root.addView(x);}
    void setup(){base();title("إعداد اللاعبين");card("اكتبوا أسماء اللاعبين ثم ابدأوا القضية.");EditText[] e=new EditText[8];for(int i=0;i<8;i++){e[i]=new EditText(this);e[i].setText(n[i]);e[i].setTextColor(WHITE);e[i].setGravity(Gravity.RIGHT);root.addView(e[i]);}Button x=b("بدء القضية");x.setOnClickListener(v->{for(int i=0;i<8;i++)n[i]=e[i].getText().toString();priv(0);});root.addView(x);}
    void priv(final int i){base();title("معلومات سرية");card("مرر الهاتف إلى: "+n[i]+"\n\nلا تسمح لأي لاعب آخر برؤية الشاشة.");Button x=b("اكشف دوري");x.setOnClickListener(v->{base();title("دورك السري");TextView rr=t(r[i],30,i>=5?RED:GREEN,true);rr.setGravity(Gravity.CENTER);root.addView(rr);card("سرك\n\n"+s[i]);card("ما تعرفه\n\n"+k[i]);card("جملتك في الجولة الأولى\n\n«"+q[i]+"»");Button nx=b(i<7?"إخفاء وتمرير الهاتف":"بدء الجولة الأولى");nx.setOnClickListener(z->{if(i<7)priv(i+1);else round1();});root.addView(nx);});root.addView(x);}
    void round1(){base();title("الجولة الأولى");card("🕵️ الأقوال\n\nكل لاعب يقرأ جملته السرية بصوت عالٍ ثم ناقشوا التناقضات.\n\nالأبرياء لديهم أسرار أيضًا. وجود سر لا يعني أن صاحبه مذنب.");Button x=b("كشف الدليل الأول");x.setOnClickListener(v->clue1());root.addView(x);}
    void clue1(){base();title("دليل جديد");card("🧩 سجل أمني تالف\n\nتم فتح الممر السري الساعة 21:43 باستخدام صلاحية خاصة. الممر لا يظهر في الخريطة العادية. بعد أربع دقائق تم تعديل جزء من سجل الكاميرات.");card("فكروا في هذا\n\nمن كان يعرف بوجود الممر؟ وهل فتحه يعني بالضرورة أنه القاتل؟");Button x=b("كشف الدليل التالي");x.setOnClickListener(v->clue2());root.addView(x);}
    void clue2(){base();title("دليل جديد");card("🧩 توقيت الشريحة\n\nتم تسجيل نقل الـCore من خزنة الذاكرة الساعة 21:47، أي بعد فتح الممر السري بأربع دقائق.\n\nفتح الممر وحده لا يثبت أن مستخدمه هو السارق.");Button x=b("المواجهة");x.setOnClickListener(v->interrogate());root.addView(x);}
    void interrogate(){base();title("المواجهة");card("اختروا لاعبًا لسؤاله. اللاعب يجيب بصوته.");for(int i=0;i<8;i++){final int j=i;Button x=o(n[i]);x.setOnClickListener(v->question(j));root.addView(x);}Button sk=o("تخطي المواجهة");sk.setOnClickListener(v->vote());root.addView(sk);}
    void question(int i){base();title("السؤال");String z=i==5?"كيف تفسر وجودك قرب منطقة التحكم؟":i==6?"لماذا كنت في المنطقة الشرقية وقت نقل الـCore؟":i==7?"لماذا تم تعديل سجل الأمن بعد الحادث؟":"ما السر الذي أخفيته عن بقية اللاعبين؟";card(n[i]+"\n\n«"+z+"»\n\nاللاعب يجيب بصوته، وأنتم تقررون هل الإجابة منطقية.");Button x=b("الانتقال للتصويت");x.setOnClickListener(v->vote());root.addView(x);}
    void vote(){base();title("التصويت");card("من الأكثر إثارة للشك؟");for(int i=0;i<8;i++){final int j=i;Button x=o("○ "+n[i]);x.setOnClickListener(v->result(j));root.addView(x);}}
    void result(int i){base();title("نتيجة التصويت");if(i<5)card("❌ اختيار خاطئ\n\n"+n[i]+" بريء.\n\n💡 تلميح: أحد اللاعبين قال شيئًا صحيحًا، لكنه أخفى جزءًا مهمًا من الحقيقة.");else card("⚠️ اكتشاف\n\n"+n[i]+" كان مذنبًا بالفعل، لكن القضية لم تنتهِ. ما زال هناك مذنبون آخرون.");Button x=b("متابعة التحقيق");x.setOnClickListener(v->round2());root.addView(x);}
    void round2(){base();title("الجولة الثانية");card("الجولة ٢ — الربط بين الأدلة\n\nهل الشخص الذي فتح الممر هو نفسه الشخص الذي سرق الـCore؟ أم أن شخصين استغلا نفس الفوضى؟");Button x=b("الاتهام النهائي");x.setOnClickListener(v->finale());root.addView(x);}
    void finale(){base();title("الاتهام النهائي");card("من تعتقدون أنه القاتل الحقيقي؟");for(int i=0;i<8;i++){final int j=i;Button x=o(n[i]);x.setOnClickListener(v->reveal(j));root.addView(x);}}
    void reveal(int i){base();title("النهاية");card(i==5?"🏆 نهاية ناجحة\n\nلقد أمسكتم بالقاتل الحقيقي!":"🕯️ نهاية غير مكتملة\n\nاتهام خاطئ. القاتل الحقيقي كان مختبئًا في مكان آخر.");card("الحقيقة\n\nالقاتل: "+n[5]+"\nالسارق: "+n[6]+"\nالمتواطئ: "+n[7]);Button x=b("العودة للرئيسية");x.setOnClickListener(v->home());root.addView(x);}
    void how(){base();title("طريقة اللعب");card("١. اختاروا القصة\nكل قضية لها شخصيات وأسرار وأدلة مختلفة.");card("٢. مرروا الهاتف\nكل لاعب يرى معلوماته الخاصة فقط.");card("٣. تحدثوا وحققوا\nاقرأوا الجمل، اسألوا بعضكم، واربطوا الأدلة.");card("٤. صوّتوا\nيمكن أن تخطئوا وتخرجوا بريئًا، وعندها تحصلون على تلميح.");Button x=b("العودة");x.setOnClickListener(v->home());root.addView(x);}
}